version: "3.9"
services:
  web:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  nginx:
    depends_on:
      - web  
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"      
