FROM python:3.7-alpine AS builder

EXPOSE 8000
WORKDIR /usr/src/app

RUN sudo apt install libpq-dev python-dev -y

COPY requirements.txt /usr/src/app

RUN pip3 install -r requirements.txt --no-cache-dir

COPY . /usr/src/app

ENTRYPOINT ["python3"] 

CMD ["manage.py", "runserver", "0.0.0.0:8000"]
